# Generated by Django 3.1 on 2021-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_label', models.CharField(max_length=10)),
                ('t1_status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('t2_status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('t3_status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('t4_status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('t5_status', models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')])),
                ('time_stamp', models.DateField()),
            ],
        ),
    ]
