# Generated by Django 3.1 on 2021-01-30 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_data_terminal_bulkupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_terminal',
            name='switch_label',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='data_terminal',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
