# Generated by Django 3.1 on 2021-01-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210130_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_terminal',
            name='switch_status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
