# Generated by Django 3.1 on 2021-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_data_terminal_switch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_terminal',
            name='email_time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_terminal',
            name='switch_status',
            field=models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')]),
        ),
    ]
